CREATE TABLE EMPLOYEE
(
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    FIRSTNAME Varchar2(2) ,
    LASTNAME Varchar2(50) ,
    DATE_OF_BIRTH DATE ,
    CompanyID INTEGER,
    CONSTRAINT EMPLOYEE_ID PRIMARY KEY (ID)

);-- TODO Create a table for Employee containing an ID, firstname, lastname and date of birth
